config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :users, only: [:show, :index]
  root 'pins#home'
  get "about" => "pages#about"
  get "tags" => "pages#tags"
  get 'tags/:tag', to: 'pins#index', as: :tag
  get 'gallery', to: 'pins#index'

end

app/models/contact.rb
#class Contact < MailForm::Base
#  attribute :name,      :validate => true
#  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
#  attribute :message
#  attribute :nickname,  :captcha  => true
#
#  # Declare the e-mail headers. It accepts anything the mail method
#  # in ActionMailer accepts.
#  def headers
#    {
#      :subject => "Pinteresting Contact Form",
#      :to => "georges.leclerc@gmail.com",
#      :from => %("#{name}" <#{email}>)
#    }
#  end
#end

app/models/pin.rb
class Pin < ActiveRecord::Base
     validates :image, presence: true
     validates :description, presence: true
     belongs_to :user
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
     acts_as_taggable_on :tags

     def next_image
        self.class.where('id > ?', self.id).order('id asc').first
     end
     def previous_image
        self.class.where('id < ?', self.id).order('id desc').first
     end
     def current_image
        self.class.where('id = ?', self.id).order('id desc').first
     end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, :presence => true,
            :on => :create,
            :format => {:with => /\A.*(?=.{10,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\@\#\$\%\^\&\+\=]).*\Z/ }
  validates :name, :presence => true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def tags
  	@tags = Pin.tag_counts_on(:tags)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :home]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    if params[:tag].present? 
      @pins = Pin.tagged_with(params[:tag], wild: true, any: true).order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
    else
      @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
    end
    @tags = Pin.tag_counts_on(:tags)
    @pin_count = Pin.count
  end

  def home
    @pins = Pin.all.order("created_at DESC").limit(20)
    @tags = Pin.tag_counts_on(:tags).most_used(25).shuffle
    @pin_count = Pin.count
    @user_count = User.count
    @tag_count = Pin.tag_counts_on(:tags).count
  end

  def tag_cloud
    Pin.find(:first).pins.tag_counts_on(:tags)
    @tags = Pin.tag_counts_on(:tags)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :tag_list)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create] # Change this to be any actions you want to protect.

  private
    def check_captcha
      if verify_recaptcha
        true
      else
        if Rails.env.production?
          self.resource = resource_class.new sign_up_params
          respond_with_navigational(resource) { render :new }
        else
          true
        end
      end 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def show
    @user = User.find(params[:id])
    @pin_count = @user.pins.count
    @pins = @user.pins.all
    @user.pins = @pins
    @user_pins = @pins.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)

  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Gallery", '/gallery' %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Welcome to my app!</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on our One Month Rails Pinteresting app</p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control", 'id'=>'fileUpload' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tags, "Tags" %><br/>
    <%= f.text_field :tag_list, value: @pin.tag_list.to_s , 'class'=>'form-control', 'data-role'=>'tagsinput', 'placeholder'=>'Add tags' %>
  </div>
  <div class="form-group" id="image-holder-div" style="display:none;">
    <%= f.label :imagePreview, "Image preview" %>
    <div id="image-holder"></div>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>


<div class="form-group">
	<%= label :existingImage, "Existing image" %><br/>
	<%= image_tag(@pin.image.url(:thumb), :class => "img-rounded") %>
</div>
<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/home.html.erb
<%= render 'pages/home' unless user_signed_in? %>



<div class="row">
  <div id="tags" class="col-xs-6 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">Popular tags</div>
      <div class="panel-body">
        <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
          <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
        <% end %>
      </div>
    </div>
  </div>

  <div id="stats" class="col-xs-6 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">Statistics</div>
      <div class="panel-body">
        <p>Number of tags: <%= @tag_count %></p>
        <p>Number of images: <%= @pin_count %></p>
        <p>Number of users: <%= @user_count %></p>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div id="pins" class="col-xs-6">
    <div class="panel panel-default">
        <div class="panel-body">
          <% @pins.each do |pin| %>
            <%= link_to image_tag(pin.image.url(:thumb), :class => "img-rounded"), pin %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= link_to pin.user.name, pin.user if pin.user %></strong></p>
        <% pin.tags.any? %>
          <p><% pin.tags.each do |tag| %>
            <span class="label label-teal">
              <%= link_to tag.name, tag_path(tag.name) %>
            </span>
        <% end %></p>
        <% if current_user && pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-xs-6 col-sm-4" id="PinDetails">

    <p>
      <% if @pin.next_image != nil %>
        <%= link_to 'Next', @pin.next_image, id: "next_pin" %>
      <% else %>
        Next
      <% end %> | 
      <% if @pin.previous_image != nil %>
        <%= link_to 'Previous', @pin.previous_image, id: "previous_pin" %>
      <% else %>
        Previous
      <% end %></p>

    <p>Added <%= time_ago_in_words(@pin.created_at) %> ago</p>
    <p><%= @pin.description %></p>
    <p><strong><%= link_to @pin.user.name, @pin.user if @pin.user %></strong></p>
    <p><% @pin.tags.each do |tag| %>
        <span class="label label-teal">
          <%= link_to tag.name, tag_path(tag.name) %>
        </span>
    <% end %></p>
    <% if current_user && @pin.user == current_user %>
       <%= link_to edit_pin_path(@pin) do %>
          <span class="glyphicon glyphicon-edit"></span>
          Edit
       <% end %>
    <% end %>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-8">
    <div id="PinPanel">
      <%= link_to image_tag(@pin.image(:original), id: "pinImage", class: "img-fluid", "style": "max-width: 100%;max-height: 100%"), @pin.image(:original), "data-lightbox": "image" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
	<li><%= link_to user.name, user %></li>
<% end %>
</ul>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>

<div id="pins" class="transitions-enabled">
  <% @user_pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= pin.user.name if pin.user %></strong></p>
        <% pin.tags.any? %>
          <p><% pin.tags.each do |tag| %>
            <span class="label label-teal">
              <%= link_to tag.name, tag_path(tag.name) %>
            </span>
        <% end %></p>
        <% if current_user && pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @user_pins, renderer: BootstrapPagination::Rails %>
</div>